In [1]:
import numpy as np
# Question 1
a = np.random.rand(10,1)
print("The mean is %f" %a.mean())


The mean is 0.557896


In [2]:
# Question 2
a = np.random.rand(20,1)
print("The variance is %f" %a.var())
print("The Standard deviation is %f"%a.std())

The variance is 0.083464
The Standard deviation is 0.288901


In [3]:
# Question 3
a = np.random.rand(10,20)
b = np.random.rand(20,25)
c = np.dot(a,b)
print("The matrix multiplication of matrix a and matrix b is: ")
print(c)
print("The product matrix is of shape", end = ' ')
print(c.shape)
print("The sum of the product matrix is %f"%c.sum())

The matrix multiplication of matrix a and matrix b is: 
[[ 4.05753904  4.13915417  4.81259322  3.92663242  4.3402027   6.38748302
   4.50335522  4.06445364  4.40812226  4.15138674  4.29583765  3.42305089
   4.47280199  3.17862176  4.26403397  4.35757112  4.75343077  4.64908472
   4.52859021  5.25688259  5.0187105   4.00708794  4.94858819  4.42608318
   4.49210792]
 [ 3.89168666  4.4505259   4.08639292  4.4280211   3.96855997  5.24275132
   5.0885596   3.67547078  4.19492495  2.86987487  3.27657926  3.35601032
   3.95422675  3.25566161  3.91599848  3.71977162  4.33676083  4.92094965
   3.40770787  4.63797716  4.13683869  3.44598406  4.33375749  3.94164576
   4.19939869]
 [ 3.46752409  4.86021691  5.62281024  4.04339772  4.85032581  7.02694329
   4.78124381  4.41282588  3.95632302  4.60841382  4.85817285  4.83494496
   5.50856947  4.04585679  4.64929209  5.10526166  5.15043667  5.11243161
   5.46321861  5.3887615   4.5872422   3.97889429  5.6208164   4.95202905
   4.81458909]
 [ 4.731509

In [7]:
# Question 4
import numpy as np
import math
a = np.arange(10).reshape(10,1)
#print (a)
def f(x):
    return 1/(1 + np.exp(-x))


re=np.apply_along_axis(f,0,a)


    

In [8]:
re

array([[ 0.5       ],
       [ 0.73105858],
       [ 0.88079708],
       [ 0.95257413],
       [ 0.98201379],
       [ 0.99330715],
       [ 0.99752738],
       [ 0.99908895],
       [ 0.99966465],
       [ 0.99987661]])

In [9]:
re.shape

(10, 1)

In [13]:
a = np.arange(10).reshape(10,1)
a

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [10]:
# Question 4
import numpy as np
import math
a = np.arange(10).reshape(10,1)
#print (a)
def f(x):
    return 1/(1 + math.exp(-x))


re=np.apply_along_axis(f,1,a)


    

In [11]:
re

array([ 0.5       ,  0.73105858,  0.88079708,  0.95257413,  0.98201379,
        0.99330715,  0.99752738,  0.99908895,  0.99966465,  0.99987661])

In [12]:
re.shape

(10,)

### 